app-catalog/src/api/releases.tsx
app-catalog/src/components/charts/EditorDialog.tsx

Description is a required in create release helm API so added it.

app-catalog: Add description to createRelease

---

app-catalog/src/components/charts/EditorDialog.tsx
app-catalog/src/components/releases/Detail.tsx
app-catalog/src/components/releases/EditorDialog.tsx

App catalog fixes

---

prometheus/src/common.tsx
prometheus/src/index.tsx

This adds charts for pvc disk usage and capacity.

prometheus: Add chart for PVC

---

.github/workflows/headlamp-plugin-github-workflow.yaml

Now runs checks for each plugin folder

workflow: Fix github workflow

---

artifacthub-repo.yml

First step to start making plugins available on ArtifactHub.

Add ArtifactHub repo file

---

example-change-logo/README.md
example-change-logo/artifacthub-pkg.yml

This plugin is from Headlamp's examples, but can be convenient for someone to try it out from the plugin catalog.

Add new plugin "example-change-logo"

---

kompose/artifacthub-pkg.yml
opencost/artifacthub-pkg.yml

opencost,kompose: Bump ArtifactHub build version

---

plugin-catalog/src/components/plugins/Detail.tsx

plugin-catalog: Allow to reload plugin on install and uninstall

---

app-catalog/src/components/charts/EditorDialog.tsx

This change adds default values to the top options in the install UI. The namespace is set initially set to default, the version to the latest version for the respective app, and the description to [app name] deployment.
Fixes: #44

app-catalog: Add default values to options

---

flux/src/common/StatusLabel.tsx

flux: Show suspended in status column

---

README.md

Updating the Obs for Observe to Notes be easier to understand for readers

readme: Update obs title

---

plugin-catalog/src/components/plugins/List.tsx

The plugin settings hide away the possibility of seeing more plugins. These changes add a switch to the plugin catalog to display/hide non-official plugins without going to the settings.
How to test:
1. Go to the plugin catalog. Notice the new switch next to the title
2. Switch it off -> See the warning/confirmation.
3. Press No -> The confirm dialog is closed and nothing happens
4. Press Yes -> The catalog is reloaded showing a lot more plugins

plugin-catalog: Add a switch to show/hide non-official plugins quickly

---

flux/src/common/Table.tsx
flux/src/inventory/index.tsx

flux: fix sorting on lastUpdated, source, age

---

README.md

this patch adds maintainer github profile 
for each plugin.

readme: Add plugin maintainers

---

flux/src/common/StatusLabel.tsx
flux/src/helm-releases/HelmReleaseList.tsx
flux/src/helm-releases/HelmReleaseSingle.tsx
flux/src/helpers/index.tsx
flux/src/image-automation/ImageAutomationList.tsx
flux/src/image-automation/ImageAutomationSingle.tsx
flux/src/kustomizations/KustomizationList.tsx
flux/src/kustomizations/KustomizationSingle.tsx
flux/src/notifications/NotificationList.tsx
flux/src/notifications/NotificationSingle.tsx
flux/src/sources/SourceList.tsx
flux/src/sources/SourceSingle.tsx

flux: image update UI improvements

---

flux/src/helpers/index.tsx
flux/src/image-automation/ImageAutomationList.tsx
flux/src/index.tsx
flux/src/overview/index.tsx

Adds the flux overview page to the flux plugin

Flux overview page

---

flux/src/flagger/availabilitycheck.tsx
flux/src/flagger/canaries.tsx
flux/src/flagger/canarydetails.tsx
flux/src/flagger/canarystatus.tsx
flux/src/flagger/deploymentprogress.tsx
flux/src/helpers/index.tsx
flux/src/index.tsx

We add the canary list view and a detail page for it in this PR

Init flagger views

---

flux/src/overview/index.tsx

Fixes https://github.com/headlamp-k8s/plugins/issues/198

flux: fix status helmrepository type oci

---

flux/src/image-automation/ImageAutomationSingle.tsx

Flux: imagepolicy reconcile should refer to imagerepository

---

Dockerfile

fixes #194 
Test by building and running the commands as mentioned in the issue by the user.

Dockerfile: Allow image to run as nonroot

---

flux/src/overview/index.tsx

Fixes iussue reported by Kingdon https://github.com/headlamp-k8s/plugins/issues/115#issuecomment-2776830898

Flux: objects without status should show as ready

---

flux/src/helm-releases/HelmReleaseSingle.tsx
flux/src/helm-releases/Inventory.tsx

Flux: show resources deployed by Helm chart

---

backstage/package-lock.json
cert-manager/package-lock.json
flux/package-lock.json
kompose/package-lock.json
minikube/package-lock.json
opencost/package-lock.json
plugin-catalog/package-lock.json
prometheus/package-lock.json

These changes bump vite in all relevant plugins to the desired 6.3.5 version.

Bump vite to 6.3.5

---

app-catalog/package-lock.json

This change bumps the prismjs dependency in app-catalog to the desired 1.30.0 version.

app-catalog: Bump dependency versions

---

keda/README.md
keda/package-lock.json
keda/src/components/scaledobjects/Detail.tsx
prometheus/src/components/Chart/Chart/Chart.tsx
prometheus/src/components/Chart/DiskMetricsChart/DiskMetricsChart.tsx
prometheus/src/components/Chart/KedaMetricsChart/KedaMetricsChart.tsx
prometheus/src/components/Chart/KedaScalerChart/KedaScalerChart.tsx
prometheus/src/index.tsx
prometheus/src/util.ts

keda: Add Support for Live Promtheus Metrics of KEDA Resources

---

app-catalog/package-lock.json
app-catalog/package.json
app-catalog/src/headlamp-plugin.d.ts
backstage/package-lock.json
backstage/package.json
backstage/src/headlamp-plugin.d.ts
cert-manager/package-lock.json
cert-manager/package.json
cert-manager/src/headlamp-plugin.d.ts
flux/package-lock.json
flux/package.json
flux/src/headlamp-plugin.d.ts
kompose/package-lock.json
kompose/package.json
kompose/src/headlamp-plugin.d.ts
minikube/package-lock.json
minikube/package.json
minikube/src/headlamp-plugin.d.ts
opencost/package-lock.json
opencost/package.json
opencost/src/headlamp-plugin.d.ts
plugin-catalog/package-lock.json
plugin-catalog/package.json
plugin-catalog/src/headlamp-plugin.d.ts
prometheus/package-lock.json
prometheus/package.json
prometheus/src/headlamp-plugin.d.ts

- **app-catalog: Update headlamp-plugin to 0.12.0**
- **backstage: Update headlamp-plugin to 0.12.0**
- **cert-manager: Update headlamp-plugin to 0.12.0**
- **flux: Update headlamp-plugin to 0.12.0**
- **kompose: Update headlamp-plugin to 0.12.0**
- **minikube: Update headlamp-plugin to 0.12.0**
- **opencost: Update headlamp-plugin to 0.12.0**
- **plugin-catalog: Update headlamp-plugin to 0.12.0**
- **prometheus: Update headlamp-plugin to 0.12.0**

Update headlamp-plugin to 0.12.0

---

minikube/src/CommandCluster/CommandDialog.stories.tsx
minikube/src/CommandCluster/CommandDialog.tsx
minikube/src/CommandCluster/DriverSelect.tsx

- **minikube: DriverSelect: Fix some type issues**
- **minikube: CommandDialog: Fix stories**
Related to:
- https://github.com/headlamp-k8s/plugins/issues/269

minikube: Fix storybook to improve testing

---

keda/src/components/common/CommonComponents.tsx
keda/src/components/scaledjobs/Detail.tsx
keda/src/components/scaledjobs/List.tsx
keda/src/components/scaledobjects/Detail.tsx
keda/src/components/scaledobjects/List.tsx

Addressing https://github.com/headlamp-k8s/plugins/pull/268#discussion_r2149412283
cc: @yolossn @sniok

KEDA: Add Reusable `KedaInstallCheck` Component

---

app-catalog/package-lock.json
backstage/package-lock.json
cert-manager/package-lock.json
flux/package-lock.json
karpenter/package-lock.json
keda/package-lock.json
kompose/package-lock.json
minikube/package-lock.json
opencost/package-lock.json
plugin-catalog/package-lock.json
prometheus/package-lock.json

This change updates the pbkdf2 dependency from 3.1.2 to 3.1.3 as desired.

Bump pbkdf2 to 3.1.3

---

kompose/src/kompose.tsx

This change replaces the regex matching in the kompose output with simple string parsing.

kompose: Replace regex with simple parsing

---

kompose/package.json

- kompose: Add package script
- kompose: Bump version to 0.1.1-beta

kompose 0.1.1 beta

---

README.md

added KAITO plugin under External plugins.

feat: add KAITO plugin

---

flux/src/helm-releases/HelmReleaseList.tsx
flux/src/image-automation/ImageAutomationList.tsx
flux/src/notifications/NotificationList.tsx
flux/src/sources/SourceList.tsx

Fixes #229 by adding some CRD versions used by older versions of Flux.

flux: add flux 2.0.0 CRD versions

---

karpenter/package-lock.json
karpenter/package.json
karpenter/src/NodeClass/Details.tsx
karpenter/src/NodePool/Details.tsx
karpenter/src/common/EditConfigButton.tsx
karpenter/src/common/resourceEditor.tsx
karpenter/src/helpers/jsonTOYAML.tsx
karpenter/src/schemas/index.tsx

This PR introduces a config editor for Karpenter CRDs.
Packages installed
1. ajv-formats
For validation ajv was the easiest to handle amongst other alternatives
Schema is used to check against the users input in addition to yaml general validations
Part of https://github.com/kubernetes-sigs/headlamp/issues/3231
[Screencast from 2025-07-09 21-34-15.webm](https://github.com/user-attachments/assets/e5a66564-830f-428c-bd89-e70140501fe0)
Full screen View
Full screen view with Validation Checks

karpenter: Config Editor with diffing and Validation support

---

keda/artifacthub-pkg.yml

this patch updates the artifacthub-pkg.yaml for
keda plugin

keda: Update artifacthub-pkg.yaml for version 0.1.1-beta

---

karpenter/src/NodeClass/Details.tsx
karpenter/src/NodePool/Details.tsx
karpenter/src/common/EditConfigButton.tsx
karpenter/src/helpers/handleDiff.tsx
karpenter/src/helpers/handleSave.tsx
karpenter/src/schemas/index.tsx

fixes #339 
[Screencast from 2025-07-23 22-59-40.webm](https://github.com/user-attachments/assets/d9074017-1aef-4e85-abf4-c1e700fdbf4e)

karpenter: Fix abrupt closing behaviour of Diff Editor

---

karpenter/README.md
karpenter/artifacthub-pkg.yml
karpenter/package-lock.json
karpenter/package.json

This PR adds configurations for release of Karpenter plugin
Related To #327 
Part of https://github.com/kubernetes-sigs/headlamp/issues/3231

karpenter: Add configs for Release

---

tools/releaser/package-lock.json
tools/releaser/package.json

This reverts commit d0403a045f36f8b75b75db2824239b3fd8ef7775.
This was creating an issue when importing.

Revert "tools/releaser: Bump @octokit/rest to 22.0.0"

---

app-catalog/package-lock.json
backstage/package-lock.json
cert-manager/package-lock.json
flux/package-lock.json
karpenter/package-lock.json
keda/package-lock.json
kompose/package-lock.json
minikube/package-lock.json
opencost/package-lock.json
plugin-catalog/package-lock.json
tools/releaser/package-lock.json

This change updates the form-data dependency to 4.0.4 as desired.

Bump form-data to 4.0.4

---

app-catalog/package-lock.json
backstage/package-lock.json
cert-manager/package-lock.json
flux/package-lock.json
karpenter/package-lock.json
keda/package-lock.json
kompose/package-lock.json
minikube/package-lock.json
opencost/package-lock.json
plugin-catalog/package-lock.json
prometheus/package-lock.json
tools/releaser/package-lock.json

This change updates the tmp dependency to 0.2.4 as desired.

Bump tmp to 0.2.4

---

karpenter/README.md

This PR fixes the YAML lint error and updates the README for Karpenter plugin
Fixes #389

karpenter: Update README
