headlamp-k8s/plugins

app-catalog/src/api/releases.tsx
We have recently restricted some backend endpoints to the use of a
token generated by the app, so this plugin was failing since it needed
to use it.
=> app-catalog: Add the backend token to the helm-related requests

app-catalog/src/components/releases/EditorDialog.tsx
The chart name was being sent as chart version and this was causing the upgrade request to fail, this patch fixes it.
=> app-catalog: Fix wrong version being used in Upgrade request

.github/workflows/headlamp-plugin-github-workflow.yaml, app-catalog/package-lock.json, app-catalog/package.json, app-catalog/src/components/charts/ChartsList.stories.tsx, app-catalog/src/components/charts/List.tsx, app-catalog/src/components/charts/__snapshots__/ChartsList.stories.storyshot, app-catalog/src/components/releases/List.tsx, app-catalog/src/components/releases/ReleaseList.stories.tsx, app-catalog/src/components/releases/__snapshots__/ReleaseList.stories.storyshot, app-catalog/src/storybook.test.tsx
This adds a couple of basic storybook stories, and enables tests on the plugins repo.
- `npm run test`
- `npm run storybook`
- note the tests are running in the github action
=> app-catalog: Add some tests

prometheus/src/common.tsx
Chart toggle buttons and play/pause buttons were not correctly aligned. Also the y-axis for all charts were going outside the div box.
=> prometheus: Fix charts CSS

prometheus/src/chart.tsx, prometheus/src/request.tsx
this patch handles the Non JSON errors that
are thrown by the k8s proxy when the pod isn't
in Ready state.
=> prometheus: Handle Non JSON errors in response

prometheus/src/common.tsx
fixes https://github.com/headlamp-k8s/headlamp/issues/1878
This PR addresses the issue where text related to the "Install Prometheus Metrics Charts" parts were not visible when using dark mode. By adjusting the text color settings for dark mode, this fix ensures that all text is clearly visible, improving usability and accessibility.
**Before**
**After**
=> frontend: Fixes the text for dark mode

prometheus/src/common.tsx
This PR addresses the issue where the pause button in the Prometheus plugin lacked a descriptive label, making it unclear to users what the button's function was upon hovering. A tooltip has been added to provide clear guidance and improve user experience.
=> Add Tooltip to Pause Button in Prometheus Plugin

app-catalog/src/components/charts/List.tsx, app-catalog/src/components/charts/__snapshots__/ChartsList.stories.storyshot, app-catalog/src/components/charts/cncf-icon-color.svg
fixes issue #20
This PR aims to enhance our app catalog by incorporating important badges from ArtifactHub. These badges indicate whether an app is official, verified, or a CNCF project. Displaying these badges will help users make informed decisions about which packages to install, ensuring they opt for secure and verified applications.
=> frontend: Add CNCF and verification badge to charts

app-catalog/src/components/charts/EditorDialog.tsx, app-catalog/src/components/releases/EditorDialog.tsx
**TLDR**: This is a quick fix for the app-catalog plugin crash with vite frontend
This will work with both webpack and vite
**Explanation:**
On the app side we expose `window.pluginLib` variable that contains modules that plugins can use without having to bundle it in the plugins. 
When plugins try to import (for example monaco editor) `import Editor from '@monaco-editor/react'` gets replaced by `const Editor = window.pluginLib.ReactMonacoEditor` in plugins built by vite  or `const Editor = webpack_require(window.pluginLib.ReactMonacoEditor)"` in plugins built by webpack (very simplified)
When frontend and plugins are built with webpack the monaco editor module will have a special "__esModule" field that will then be recognized by `webpack_require` function on the plugin side. But vite …
=> app-catalog: Fix vite crash by using named import for monaco editor

app-catalog/src/components/charts/EditorDialog.tsx, app-catalog/src/components/releases/EditorDialog.tsx
This rollbacks #47 
Apparently when building frontend with webpack, the named export 'Editor' is missing for whatever reason.
This rollbacks to just using default export since it now works on main (with vite)
=> app-catalog: Rollback #47. Use default export of the monaco-editor

app-catalog/src/api/releases.tsx, app-catalog/src/api/repository.tsx
Instead of relying on the URL search params.
=> app-catalog: Use the getHeadlampAPIHeaders from headlamp-plugin/lib

opencost/src/__snapshots__/details.stories.storyshot, opencost/src/detail.tsx, opencost/src/index.tsx
the header action was breaking the app and it
is fixed now.
before:
https://github.com/user-attachments/assets/2f599f23-116e-482a-9838-4c15c0aa500d
after:
https://github.com/user-attachments/assets/fe2c62fc-0c50-4128-964b-50b90779c8e8
=> opencost: Fix the Details View Header Action

opencost/src/index.tsx
this patch removes the use of hooks in the registerResourceTableColumnsProcessor 
fixes: #83
=> opencost: Remove hooks usage in registerResourceTableColumnsProcessor

app-catalog/src/components/charts/List.tsx
This change removes a reference to undefined props which is causing the app-catalog to crash.
Fixes: #92
=> app-catalog: Remove unused props

plugin-catalog/src/components/plugins/Detail.tsx
This is also shown when the plugin is removed.
=> plugin-catalog: Replace "Activate Now" by "Reload Now"

app-catalog/src/components/charts/EditorDialog.tsx
This change fixes a regression caused by #94 where the app-catalog would crash on the install dialog. We now allow the dialog to display the chart version in the case where the selectedVersion is not initialized.
=> app-catalog: Allow dialog to display chart version

prometheus/package-lock.json, prometheus/package.json, prometheus/src/components/Chart/common.tsx, prometheus/src/index.tsx, prometheus/src/util.ts
The plugin was renamed but not its settings, so the settings were never rendered.
=> Fix prometheus plugin settings

app-catalog/package-lock.json, app-catalog/package.json, app-catalog/src/components/charts/EditorDialog.tsx, app-catalog/src/components/charts/List.tsx, app-catalog/src/components/releases/EditorDialog.tsx
fixes https://github.com/headlamp-k8s/headlamp/issues/2618
1. Try to install any chart -> now it works
1. Open the app-catalog and click the X next to the All category -> no crash, the All word goes away but the apps are still there
1. Click Install on a chart, then type a release name
2. Change the version
3. Realize that the values editor was reloaded but the release name is the same
1. Go to an installed version and click Update
2. Verify that a spinner is shown until the versions are fetched
1. Go to an installed version and click Update
2. When the versions are loading -> the Update button is disabled
1. Go to an installed version and click Update
2. After the versions are loaded -> check that the versions are shown with the most recent at the top
=> Fixes for app catalog

plugin-catalog/src/components/plugins/InstalledList.tsx
This is related to #117 , but just adds a link to the plugin settings view which shows all installed plugins.
Until #117 is in a state we can merge, I think this is a simple enough change to mitigate the confusion between the 2 installed views.
=> plugin-catalog: Add link to all plugins from installed list

plugin-catalog/src/components/plugins/List.tsx, plugin-catalog/src/components/plugins/PluginCard.tsx
This change adds a label in the card for plugins with available updates. The "Installed" label now gets replaced with "Update available" in this case.
Fixes: #138
=> plugin-catalog: Add update available label to card

prometheus/src/components/Chart/CPUChart/CPUChart.tsx, prometheus/src/components/Chart/Chart/Chart.tsx, prometheus/src/components/Chart/FilesystemChart/FilesystemChart.tsx, prometheus/src/components/Chart/GenericMetricsChart/GenericMetricsChart.tsx, prometheus/src/components/Chart/MemoryChart/MemoryChart.tsx, prometheus/src/components/Chart/NetworkChart/NetworkChart.tsx, prometheus/src/components/Chart/common.tsx
=> prometheus: Update look and add interval selector

app-catalog/src/components/charts/List.tsx
This PR fixes a bug in the `App-Menu` plugin that caused singular cards to render squished. The issue affected the visual appearance and usability of the cards, especially when only one card was present. 
1. **Fixed Card Rendering**:
- Updated the rendering logic to ensure singular cards display correctly without being squished.
- Improved the layout to make card sizes consistent regardless of the number of cards.
2. **Improved Card Sizing**:
- Adjusted the size and spacing of cards to enhance the overall user experience.
- Ensured that the layout remains visually appealing across various card counts and screen sizes.
Before
After
---
1. Navigate to the `App-Menu` plugin in the application.
2. Test the rendering of cards in the following scenarios:
- Search for `Headlamp` and filter 
3. …
=> app-catalog: fix and updates cards styles

prometheus/src/components/Chart/common.tsx
Fixes the runtime error in PrometheusNotFoundBanner component by migrating to MUI v5 styles components.
=> prometheus: Fix errors due to deprecated makeStyles

flux/src/runtime/RuntimeList.tsx
The runtimes were trying to compare a value from the labels when they may not be set.
=> flux: Fix crash in runtimes when no labels are available

README.md, cert-manager/artifacthub-pkg.yml
this patch adds the artifacthub package for the cert-manager plugin
=> cert-manager: Add artifacthub package

flux/src/helpers/index.tsx
Users are normally interested in the most recent events. Events should therefore be sorted on timestamp with the newest event on top.
=> flux: sort events on timestamp

app-catalog/README.md
This PR makes improvements to the current README for the App Catalog plugin, it expands on the details of the plugin's functionality and includes start up guide and visual references.
Link to after changes
https://github.com/headlamp-k8s/plugins/tree/update-app-catalog-readme/app-catalog
=> app-catalog: Improve the README for app-catalog

flux/src/common/StatusLabel.tsx
A kustomization waiting for another Kustomization is currently shown with status Error. 
Waiting for another kustomization is however not an error. It is better shown as a warning with a status shown as 'Waiting'.
=> flux: show kustomization status as warning when DependencyNotReady

prometheus/src/index.tsx
Currently memory usage is doubled because cadvisor is taking the values from cgroups which contains the parent group.
The parrent group accumulates the memory, so we need  to ignore the parent.
https://stackoverflow.com/a/69282328/10109857
- closes headlamp-k8s/headlamp#2920
=> prometheus: fix doubled memory usage

flux/src/common/Table.tsx, flux/src/helm-releases/HelmReleaseSingle.tsx, flux/src/helpers/index.tsx, flux/src/kustomizations/KustomizationSingle.tsx, flux/src/sources/Source.tsx
Respect that the source ref can point to a different namespace.
- closes #177
=> flux: fix source ref namespace

prometheus/src/components/Chart/CPUChart/CPUChart.tsx, prometheus/src/components/Chart/Chart/Chart.tsx, prometheus/src/components/Chart/DiskChart/DiskChart.tsx, prometheus/src/components/Chart/DiskMetricsChart/DiskMetricsChart.tsx, prometheus/src/components/Chart/FilesystemChart/FilesystemChart.tsx, prometheus/src/components/Chart/GenericMetricsChart/GenericMetricsChart.tsx, prometheus/src/components/Chart/MemoryChart/MemoryChart.tsx, prometheus/src/components/Chart/NetworkChart/NetworkChart.tsx, prometheus/src/components/Settings/Settings.tsx, prometheus/src/request.tsx, prometheus/src/util.ts
this patch adds support for configuring subpath, this is helpful for users who use mimir/victoria metrics. these tools make the prometheus compatible api avaialble in /prometheus path and the plugin can be configured to fetch metrics from these sources.
=> prometheus: Add support for configuring subpath

plugin-catalog/src/components/plugins/List.tsx
How to test:
1. Open devtools -> Application -> Storage -> Click "Clear site data"
2. go to plugin catalog
3. Click on official toggle
4. Confirm popup
5. Toggle should be off
=> plugin-catalog: Fix official switch logic

.github/workflows/build-and-publish-image.yml
This is based on #172 but is limited to building and publishing the image.
I believe we need to have what's in #172 but we need to do it in separate actions because, e.g. if the image fails, we shouldn't resort to doing things locally.
In the future we may trigger this workflow from a tag push.
=> github: Add workflow to build and publish container image

flux/src/flagger/canaries.tsx
A quick fix on how we get the A/B test values from flagger
=> Fix A/B testing check

minikube/src/CommandCluster/CommandCluster.tsx
- in this branch minikube/ folder `npm start`
- Then in the app, go to load cluster.
- Start adding a cluster. 
- Then when it starts running... Try to navigate away from the page. You should see a warning message, click ok to leave (cancel to not leave).
( Uses [React Router Prompt component](https://v5.reactrouter.com/core/api/Prompt) )
=> minikube: CommandCluster: Add warning if leaving and command is still running

minikube/src/CommandCluster/CommandDialog.tsx
- Add generation of cluster name by default (minikube, minikube-1, minikube-2, etc)
- Add validation for existing cluster names
- npm start
- Load Cluster
- Add minikube cluster
- See that the name is minikube-1 or so.
- Enter an existing cluster name, and see an error, 
- prevented from using form to create with existing name
---
=> minikube: Add default cluster name, and validation for existing cluster names

flux/src/overview/index.tsx
In PR https://github.com/headlamp-k8s/plugins/pull/199 the status of oci repos on the overview page was fixed. However the status in TileChart was missed. 
This PR fixes also the status in the TileChart.
=> Flux: fix oci repo status in overview page

plugin-catalog/src/components/plugins/Detail.tsx
These changes address minor bugs in the plugin catalog UI.
Fixes #3157 #3163
- https://github.com/kubernetes-sigs/headlamp/issues/3157
- https://github.com/kubernetes-sigs/headlamp/issues/3163
=> plugin-catalog: Fix UI bugs

prometheus/src/components/Chart/CPUChart/CPUChart.tsx, prometheus/src/components/Chart/Chart/Chart.tsx, prometheus/src/components/Chart/Chart/chart.stories.tsx, prometheus/src/components/Chart/DiskChart/DiskChart.tsx, prometheus/src/components/Chart/DiskMetricsChart/DiskMetricsChart.tsx, prometheus/src/components/Chart/FilesystemChart/FilesystemChart.tsx, prometheus/src/components/Chart/GenericMetricsChart/GenericMetricsChart.tsx, prometheus/src/components/Chart/MemoryChart/MemoryChart.tsx, prometheus/src/components/Chart/NetworkChart/NetworkChart.tsx, prometheus/src/components/Settings/Settings.tsx, prometheus/src/util.test.ts, prometheus/src/util.ts
The official Prometheus Query UI accepts resolution as an input from the user:
It will be better if we also allow Headlamp to accept such an input. This will help us in calculating the step size at runtime based on `timeRange` and `resolution` rather than hard coding it like we are currently doing it at [this](https://github.com/headlamp-k8s/plugins/blob/main/prometheus/src/util.ts#L250-#L279) place. 
The inspiration for dynamic step size calculation has been taken from the [official Prometheus' UI code](https://github.com/prometheus/prometheus/blob/main/web/ui/mantine-ui/src/state/queryPageSlice.ts#L28-#L50)
cc @yolossn
=> prometheus: Add resolution input for metrics

.github/workflows/headlamp-plugin-github-workflow.yaml
This change limits the permissions of the GITHUB_TOKEN as desired.
=> github/workflows/headlamp-plugin-github-workflow: Limit token perms

README.md
So people might discover external plugins more easily.
Adds below to the README.
---
These are some of the plugins maintained outside of the plugins repo by others.
Please see [headlamp plugins on Artifact Hub](https://artifacthub.io/packages/search?kind=21&sort=relevance&page=1) for a list of plugins published there.
| Plugin | Description | Notes | Maintainers |
| ---------------------------------- | ---------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------- | ----------- |
| [inspektor-gadget](https://github.com/inspektor-gadget/headlamp-plugin/) | This is a Headlamp plugin exposing and show-casing IG gadgets. |  | …
=> README: Add links to some external plugins

.github/workflows/scorecard-analysis.yml, README.md
- .github: scorecard-analysis: Add config for OpenSSF scorecard
- README: Add OpenSSF scorecard badge
This is required for CNCF projects at the incubated stage.
Additionally, once merged it gives more code scanning results in the Security tab -> Code Scanning section on github.
https://github.com/headlamp-k8s/plugins/security/code-scanning
Once merged click on the badge in the README.
Note, `headlamp-k8s/plugins` isn't already scanned by OpenSSF, so it does not have data for it yet.
To get the data, the action will have to be run manually the first time, OR wait for the badge results to be updated once daily.
The action is run daily via github action cron.
We use it in the headlamp repos, and it uses the OpenSSF template for the workflow.
=> .github: README: Add OpenSSF scorecard badge

flux/src/helpers/index.tsx, flux/src/overview/index.tsx
=> flux: Fix overview page fetching resource classes

flux/package-lock.json
This change bumps the undici dependency in the flux plugin to the desired version.
=> flux: Bump undici to 6.21.3

plugin-catalog/src/components/plugins/InstalledList.stories.tsx, plugin-catalog/src/components/plugins/InstalledList.tsx
Solves Issue: [#2586](https://github.com/headlamp-k8s/headlamp/issues/2586)
This PR addresses the issue observed during our ContribuFest at KubeCon, where users expressed confusion about the `Installed` view in the Plugin Catalog. Specifically, users were expecting to find their development plugins in the `Installed` view, but only plugins installed via the Plugin Catalog were listed. 
To resolve this, this PR proposes the following updates:
- **Unified Installed View**: The `Installed` view in the Plugin Catalog will now display all installed plugins, regardless of their installation source.
- **Categorization**:
- Plugins installed via the Plugin Catalog will appear under a section titled `Installed from the Plugin Catalog`.
- Plugins installed from other sources will appear under a …
=> plugin-catalog: Rework installed list to include all plugins

SECURITY.md
This change adds a security policy to the plugins repo with the SECURITY.md file, aligned with the framework of OpenSSF.
Fixes: #266
=> Add security policy with SECURITY.md

.github/workflows/headlamp-plugin-github-workflow.yaml
This is the version we are using in the headlamp repo.
=> github: Update CI checks to use node to LTS version 22.x from 18.x

README.md
Adds Gatekeeper plugin
https://artifacthub.io/packages/headlamp/gatekeeper-headlamp-plugin/gatekeeper
https://github.com/sozercan/gatekeeper-headlamp-plugin
=> add gatekeeper plugin to external plugins

minikube/src/CommandCluster/CommandCluster.tsx
By default minikube stop removes the context from the .kube/config
file, which means that it is not displayed on the home screen. The user can not start it up again.
Note: This plugin now stops minikube with `minikube stop --keep-context-active true`.
---
Before:
After:
_This screen shot shows that after stopping minikube with headlamp that it is still listed on the home screen._
---
Related to:
- https://github.com/headlamp-k8s/plugins/issues/269
- `cd minikube && npm i && npm start`
- start app version of headlamp (`cd app && npm i && npm start`)
- Stop a minikube cluster with headlamp (not on command line).
- See that it's still listed on the home screen.
- Start the minikube cluster again.
=> minikube: Fix stop to leave context in .kube/config

.github/workflows/build-and-publish-image.yml
This change sets top level permissions in the build-and-publish-image workflow as desired.
=> github/workflows/build-and-publish-image: Set top level permissions

keda/package-lock.json
This change updates the following dependencies for the KEDA plugin:
- undici from 6.21.1 to 6.21.2
- vite from 6.2.1 to 6.2.7
=> KEDA: Update dependencies

.github/workflows/build-and-publish-image.yml
- Fixed Multi-Architecture Builds: Corrected multi-architecture build issues for broader platform compatibility.
- Bumped the version of the BASE NODE image(because the previous one is unsupported by some packages)
- Add an option to build one, few or all plugins by run one workflow
https://github.com/kksudo/plugins/actions/runs/15802543339
---
Split [this](https://github.com/headlamp-k8s/plugins/pull/290) PR.
https://github.com/headlamp-k8s/plugins/pull/290#issuecomment-2994200788
=> Optimized Docker Builds, Workflow,

flux/src/helm-releases/Inventory.tsx, flux/src/kustomizations/Inventory.tsx
Due to the types not being defined, a typo ("endswith" instead of "endsWith") was being covered and led to issues when running.
=> flux: Add types and fix unknown string function in Inventory

karpenter/src/NodePool/Details.tsx, karpenter/src/NodePool/List.tsx, karpenter/src/helpers/instanceRequirements.tsx, karpenter/src/helpers/parseRam.tsx, karpenter/src/helpers/renderBudgets.tsx, karpenter/src/helpers/tooltip.tsx, karpenter/src/index.tsx
This PR introduces comprehensive support for visualizing Karpenter NodePool resource within the Headlamp UI.
Part of https://github.com/kubernetes-sigs/headlamp/issues/3231
[Screencast from 2025-06-20 22-53-54.webm](https://github.com/user-attachments/assets/442cac13-d495-4abd-8114-a7aa196c96ac)
=> karpenter: NodePools: Visualize NodePool resource of Karpenter

Dockerfile
This change converts the `npm install` call to `npm ci`, which is faster, cleaner, and more secure.
=> Dockerfile: Use npm ci instead of npm install

flux/src/helpers/pluralName.tsx, flux/src/index.tsx, flux/src/overview/index.tsx
We want the failed status to be shown first thing in the overview. This PR takes the failed ones and shows them first and then the rest. We also fix the pluralName to call for functions when the kind could be undefined.
=> flux: Fix pluralName helper and update how we show overview

karpenter/src/PendingPods/Events.tsx, karpenter/src/PendingPods/List.tsx, karpenter/src/PendingPods/index.tsx, karpenter/src/index.tsx
This PR introduces a dashboard view to observe Pending Pods and observe the reason behind the pending status.
Part of https://github.com/kubernetes-sigs/headlamp/issues/3231
[Screencast from 2025-07-18 01-34-51.webm](https://github.com/user-attachments/assets/4aec7272-f42b-4a54-821f-bde5d436e63b)
=> karpenter: Dashboard for pending pods

tools/releaser/package-lock.json, tools/releaser/package.json, tools/releaser/src/commands/artifacthub.ts, tools/releaser/src/commands/build-package.ts, tools/releaser/src/commands/bump.ts, tools/releaser/src/commands/list.ts, tools/releaser/src/commands/package.ts, tools/releaser/src/commands/release.ts, tools/releaser/src/commands/tag.ts, tools/releaser/src/index.ts, tools/releaser/src/utils/artifacthub.ts, tools/releaser/src/utils/github.ts, tools/releaser/src/utils/plugin.ts, tools/releaser/tsconfig.json
This change follows up on missing updates in #322 after bumping @octokit/rest to the new ESM-only v22.
To support this new version, the tools/releaser directory is migrated to ESM:
- Switched the `tsconfig.json` to `"module": "node16"` and `"moduleResolution": "node16"`
- Added `"type": "module"` to `package.json`
- Updated all imports to use `.js` extensions for local modules
- Replaced CJS globals (`__dirname`, `__filename`) with ESM shims
=> tools/releaser: Bump @octokit/rest to 22.0.0

app-catalog/package-lock.json, backstage/package-lock.json, cert-manager/package-lock.json, flux/package-lock.json, karpenter/package-lock.json, keda/package-lock.json, kompose/package-lock.json, minikube/package-lock.json, opencost/package-lock.json, plugin-catalog/package-lock.json, prometheus/package-lock.json
This change updates the sha.js dependency to 2.4.12 as desired.
=> Bump sha.js to 2.4.12

ai-assistant/package-lock.json, ai-assistant/package.json
This change updates the prismjs dependency in the ai-assistant plugin to 1.30.0 as desired.
=> ai-assistant: Bump prismjs to 1.30.0

ai-assistant/src/components/assistant/AIInputSection.tsx
Update Enter handling in the AI Assistant input to prevent accidental submits during IME composition.
Verified with Traditional Chinese and Japanese IMEs on macOS.
=> ai-assistant: Prevent submit during IME composition
